export const WEATHER_CODES = {
    0: '☀️ Despejado',
    1: '🌤️ Principalmente despejado',
    2: '⛅ Parcialmente nublado',
    3: '☁️ Nublado',
    45: '🌫️ Neblina',
    48: '🌫️ Neblina con escarcha',
    51: '🌧️ Llovizna ligera',
    53: '🌧️ Llovizna moderada',
    55: '🌧️ Llovizna intensa',
    61: '🌧️ Lluvia ligera',
    63: '🌧️ Lluvia moderada',
    65: '🌧️ Lluvia fuerte',
    71: '❄️ Nieve ligera',
    73: '❄️ Nieve moderada',
    75: '❄️ Nieve fuerte',
    77: '❄️ Granizo',
    80: '🌦️ Chubascos ligeros',
    81: '🌦️ Chubascos moderados',
    82: '🌧️ Chubascos fuertes',
    95: '⛈️ Tormenta',
    96: '⛈️ Tormenta con granizo',
    99: '⛈️ Tormenta severa'
};